### ISSUE TITLE
FactionsPlus have a problem with MassiveCore

### ISSUE THREAD

**Issue by AnonymousMW3** [MarkehMe/FactionsPlus#175] opened 2014-12-13 10:07 UTC
Version of FactionsPlus: 0.7.1(the last build)
Version of Factions: 2.7.4(the last build)
Version of MassiveCore: 2.7.4(the last build)
Version of Spigot: 1.8(the last build)
Pastebin of the error: http://pastebin.com/9y8RX7hn
Please read, i think if it's important!

**Comment by coolemiel** [comment] 2015-01-01 21:04
Same problem here! Really annoying...

**Comment by AnonymousMW3** [comment] 2015-01-02 10:54
I hope that there will soon be an update!

**Comment by MarkehMe** [comment] 2015-01-13 11:22
Duplicate of #172

**Closed by MarkehMe** 2015-01-13 11:22 UTC
